### PR TITLE
Create language_level_df.R

### LINKED ISSUE #1: new function: reduce dialects to language-level
Here is a draft of a function that could be in this pacakge: https://github.com/HedvigS/personal-cookbook/blob/main/R/language_level_df.R

In cases where a dataset, like grambank, contains more than one dialect for the same language it reduces them to 1 per language. There are three different methods for this: 

- combine_random = combine all datapoints for all the dialects and if there is more than one datapoint for a given feature/word/variable choose randomly between them
- singular_random = choose randomly between the dialects
- singular_least_missing_data = choose the dialect which has the most datapoints 

The current version just relies on there existing a wide value table with Language_ID in the environment. @xrotwang suggested re-writing it to take SQL input instead. I leave it up to @SimonGreenhill to decide how to proceed.

### PR DESCRIPTION
**Pull request by HedvigS**
closes #1

### CODE REVIEW

**Comment by HedvigS** [comment]
I am going to write more functions for this package, and I am going to base branches on this branch since this function is useful in them.

**Comment by HedvigS** [comment]
test added.

Another step that could be taken here is to change language_level_df() to take long tables as well/instead of just wide tables as is its current behaviour.

**Comment by HedvigS** [comment]
I'm reworking the function now to just take long format.

**Comment by HedvigS** [comment]
The function language_level_df() now takes ValueTable in a long format instead of wide.

NB, I'm not changing the column "ID" in the ValueTable, which is a combination of Parameter_ID and Language_ID. I am however changing the Language_ID column. If you want,  I can set it  so that it also change sthe  ID column, up to you.

**Comment by HedvigS** [comment]
@SimonGreenhill where are the comments I should work through?

**Comment by SimonGreenhill** [comment]
[here](https://github.com/grambank/rgrambank/blob/fb258d2ad3117a0f0ec016729ee7d295c5b6a502/R/language_level_df.R) in the binarise branch. I was working over there as those functions seem to be needed there as well.

**Comment by HedvigS** [comment]
> [here](https://github.com/grambank/rgrambank/blob/fb258d2ad3117a0f0ec016729ee7d295c5b6a502/R/language_level_df.R) in the binarise branch. I was working over there as those functions seem to be needed there as well.

Aha, okay. I'll go over there and work on the two in unison then.

**Pull request closed without merging**
